version: "3.7"

services:
  application:
    container_name: sms-guide
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - ~/.ssh:/home/vscode/.ssh:ro

    ports:
      - 4000:4000
      - 35729:35729

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
